### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Ranyhyn** [joakibj/tswrdb#5] opened 2014-02-25 03:09 UTC
Hey, I've tinkered a bit with trying to get this to work, and it keeps throwing up this error whenever I try to export something (forgive the formatting, it's a mess).

EDIT: I know a nullpointer exception indicates that a variable is empty that shouldn't be, but I'm using the commands you've supplied in the readme, and getting this output. So I'm a bit confused here.

java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:112)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:108)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:262)
        at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:108)
        at com.joakibj.tswrdb.rdb.export.RdbDataExporter.<init>(RdbDataExporter.scala:21)
        at com.joakibj.tswrdb.rdb.export.RdbGenericDataExporter.<init>(RdbGenericDataExporter.scala:24)
        at com.joakibj.tswrdb.rdb.export.RdbGenericDataExporter$.apply(RdbGenericDataExporter.scala:21)
        at com.joakibj.tswrdb.commands.ExportCommands$RdbTypeExportCommand.execute(ExportCommands.scala:29)
        at com.joakibj.tswrdb.CommandDispatcher.execute(CommandDispatcher.scala:45)
        at com.joakibj.tswrdb.CommandDispatcher.dispatch(CommandDispatcher.scala:31)
        at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:93)
        at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:92)
        at scala.Option.map(Option.scala:145)
        at com.joakibj.tswrdb.TswRdb$delayedInit$body.apply(TswRdb.scala:91)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at com.joakibj.tswrdb.TswRdb$.main(TswRdb.scala:27)
        at com.joakibj.tswrdb.TswRdb.main(TswRdb.scala)

Exception in thread "main" java.lang.NullPointerException
        at com.joakibj.tswrdb.commands.ExitCommands$class.exit(ExitCommand.scala:21)
        at com.joakibj.tswrdb.commands.ExportCommands$RdbTypeExportCommand.exit(ExportCommands.scala:22)
        at com.joakibj.tswrdb.commands.ExportCommands$RdbTypeExportCommand.execute(ExportCommands.scala:24)
        at com.joakibj.tswrdb.CommandDispatcher.execute(CommandDispatcher.scala:45)
        at com.joakibj.tswrdb.CommandDispatcher.dispatch(CommandDispatcher.scala:31)
        at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:93)
        at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:92)
        at scala.Option.map(Option.scala:145)
        at com.joakibj.tswrdb.TswRdb$delayedInit$body.apply(TswRdb.scala:91)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at com.joakibj.tswrdb.TswRdb$.main(TswRdb.scala:27)
        at com.joakibj.tswrdb.TswRdb.main(TswRdb.scala)

**Comment by joakibj** [comment] 2014-02-25 08:16
I'll take a look at this when I get home from work. There is a possibility that Funcom might have changed things up in their data structures.

**Comment by joakibj** [comment] 2014-02-25 16:35
Okay, I was able to reproduce the problem. Basically it fails with this stack-trace if the directory you point tswrdb at is wrong.

The examples in the README are for my own setup, you need to point tswrdb to your own TSW installation (either Live or TestLive)

Example from the README:

`java -jar tswrdb-0.0.1.jar export rdbtype 1010042 --tsw """D:\Programs\TSW TestLive"""`

Note the triple """ (quotation mark) for the path there for msysgit shell or " single quotation mark for ordinary cmd.exe. I've forgotten to update the README after a change I made earlier.

So correct for cmd.exe is:

`java -jar tswrdb-0.0.1.jar export rdbtype 1010042 --tsw "C:\path\to\your\TSW\installation"`

If you installed TSW at `C:\Program Files (x86)\Funcom\The Secret World` it would be:

`java -jar tswrdb-0.0.1.jar export rdbtype 1010042 --tsw "C:\Program Files (x86)\Funcom\The Secret World"`

Please let me know if this helped you

**Comment by Ranyhyn** [comment] 2014-02-25 18:31
Yeah I did use my own installation directory of course, but it didn't seem to do the job.

Command I'm issuing:

F:\tswext>java -jar tswrdb.jar export rdbtype 1010042 --tsw "M:\Games\FunCom\
The Secret World\"

(note, i renamed the .jar file so it's easier to type every time i issue the command. I've verified it works, using the --version command and it does work, but the export doesn't, i'm afraid).

Which is the directory to my TSW root. I've also tried pointing it directly to the RDB directory, to no avail.

I did however install a hex editor and had a look at the rdb files one by one, and searched for some info I was interested in, and did find some of it. I'd still like to extract them as proper files, but it's yielded some good results so far.

Anyway, thanks for your help, shame it doesn't seem to work. If you've got any other ideas, I'm all ears.

P.S: I'm running it in on a windows 7 platform, and I noticed I have both java 6 and 7 installed, might that have something to do with the problem?

**Comment by joakibj** [comment] 2014-02-25 18:38
Aha, derp. Try removing the trailing backslash `\`. I believe it escapes the " quotation mark in cmd.exe. E.g.:

`java -jar tswrdb.jar export rdbtype 1010042 --tsw "M:\Games\FunCom\The Secret World"`

Alternatively, just flip them over since it works both ways in windows:

`java -jar tswrdb.jar export rdbtype 1010042 --tsw "M:/Games/FunCom/The Secret World/"`

**Comment by Ranyhyn** [comment] 2014-02-25 18:58
Ah, well I'll be damned. That's what was wrong. Thanks for the help!

I should have figured it was that simple, but there you go. Thanks for making this tool btw!

**Comment by joakibj** [comment] 2014-02-25 19:05
Excellent! No problem :+1: 

I'll revisit this soon and give it a more sane error message for these kind of things...

There is a lot of different file types and frankly a lot of garbage data there. Please let me know if there are any specific file types you are looking for. The list --all command can be helpful as well.

My favorite is poking around in the string collections to see what kind of new kind of content is yet unrevealed... :)

Anyways, I'll close this since the issue is resolved. Just make a new issue or send me an email if you have any other troubles / need help.

**Closed as completed by joakibj** 2014-02-25 19:05 UTC
Labels: question
